### ISSUE TITLE
retina images

### ISSUE THREAD

**Issue by joshreisner** [better-yet/www#1]

**Comment by katejhowe** [comment]
hi, I'm here!

**Comment by joshreisner** [comment]
Ok so looks like the images are all pretty much retina-ified except for some of the project thumbnails, because the images that are up there are smallish. I see a number of them that are 495px wide. In that one-third context, they should be 720px. Project detail images should be at least 1500px across.

To be future-proof, I'd upload 2000px wide images, like the ones you added to the Services page, since WP will scale them down for the context.

If you run into any problems, lmk.
