### ISSUE TITLE
launching

### ISSUE THREAD

**Issue by joshreisner** [better-yet/www#10]
I think we're good to go!
* Google Analytics installed (you're added)
* 404 error page all set (it just redirects to the home page)
* favorites icon
* 'Discourage search engines' unchecked
* Meta description (Better Yet is a strategic creative studio. We design projects to engage and motivate your audiences.)
* IE 9+ once-over

Things I don't think we need to bother with for phase 1:
* Accesibility for user with disabilities
* Dynamic XML sitemaps

What do you think? Should we redirect left-right.co here?

**Comment by katejhowe** [comment]
Almost! A couple more formatting items - I think I wrote a note earlier that I must not have saved. 
1. Sorry, I did go a tad too small with to nav. Can we go back to:
Top nav : 20px
sub nav: 11px
Project titles 11px

2. Project text: 
Can we try Moderat at 12px, line height 1.3 for the project text
then shift the tags to Roboto 11px 

3. Make the purple a tiny bit more subdued... like #6e34c7

4. Services and Contact, Moderat text a bit smaller. Let's try 22px, 1.2 line height

5. What do you think about an automatic animation that would take you from the landing Profile page to projects. Like after you've have 15 seconds or something to read, the project images tile in? That's one thing I love about KHMT site - you get there and just when you think there's nothing there, everything flies in. This is a bit different; I like landing on the overview, but I worry its not jazzy enough to leave people there. 

Also, do you think there's enough content? I guess we can launch and add more. Are there any projects of yours that you want to add? Definitely beefing up the digital portfolio would be good. We can certainly work on Meeting Guide and add that in.

After all that I think we should launch! and yes, redirecting left-right sounds good.

**Comment by joshreisner** [comment]
Ok, those CSS changes are done now. I think the project description is too small to read comfortably now, and think we ought to embiggen it. I wouldn't mind enlarging the fonts everywhere, but in particular on the descriptions.

I understand the desire to move people along to the profile page, but don't like the idea of moving them automatically. How about adding a link at the bottom of the text? We could emphasize it visually, and/or animate it in after a few seconds, to draw the user's attention to it.

I think the amount of content is fine! It's a version 1.0 after all. I'd love your help positioning Meeting Guide. It's not something I've attempted even on my own site. Most of my other work for the past several has been incremental improvements to existing properties. I'll send you a list of links in an email.

**Comment by katejhowe** [comment]
Yes, agree about embiggening project description (13px) , as well as project title (what was it before? I think it was good.) I think the other sizes look pretty good.

Can we reduce the vertical padding between the projects in the grid a little? - about 20-25% total. A small amount of the padding above the project title, and the rest below.

For now I put a link at the bottom of the intro text. I want to think a bit more about this going forward...

I'm looking forward to getting involved with Meeting Guide! The week after next, I have no plans ;-)

Otherwise, I think we're good to go live!

**Comment by joshreisner** [comment]
Ok I made the CSS changes. I also added a class of 'hello' to the link that makes the page wait five seconds and then animate it in. It's still not very emphatic, but LMK what you think. I think it should prompt people to move on without stealing their attention.

**Comment by katejhowe** [comment]
Cool - I like the animation for now. I like all the motion on the site, I
meant to tell you before that it all looks really good.

Good to go I say!

Do you think the black and white thumbnails look too drab? I'm thinking I
should maybe change those to color... But anyway, I can noodle around with
that after it is live.

Awesome! Thanks for being amazing at what you do.

Kate



On Thu, Jun 16, 2016 at 7:43 PM, Josh Reisner <notifications@github.com>
wrote:

> Ok I made the CSS changes. I also added a class of 'hello' to the link
> that makes the page wait five seconds and then animate it in. It's still
> not very emphatic, but LMK what you think. I think it should prompt people
> to move on without stealing their attention.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/better-yet/www/issues/10#issuecomment-226645000>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AS-I4_nLX1PFCLUeSuOQhtJerjFTNAlZks5qMd-pgaJpZM4I296t>
> .
>



-- 
- - - - - - - - - - - - - - - - - - - - - - - - - - -
kate howe makes things
- - - - - - - - - - - - - - - - - - - - - - - - - - -
tel. 1 203 415 0578
www.katehowemakesthings.com
- - - - - - - - - - - - - - - - - - - - - - - - - - -
