### ISSUE TITLE
contact page

### ISSUE THREAD

**Issue by joshreisner** [better-yet/www#2]

**Comment by katejhowe** [comment]
HOw about this? 3 columns, left is text, right two are pictures...
[BetterYet_contact.pdf](https://github.com/better-yet/www/files/311104/BetterYet_contact.pdf)

**Comment by joshreisner** [comment]
Ok thanks! I don’t think I have the margins quite right yet. Currently they’re evenly distributed and standardized with the other layouts. Let’s review margins and font sizes later this week.

https://better-yet.com/contact <https://better-yet.com/contact>

You can edit your location on your user profile page in WP. Weather and time zone will be handled automatically.

It’d be fun at some point to make an app that background-updates this.
