### ISSUE TITLE
refined list of project types

### ISSUE THREAD

**Issue by katejhowe** [better-yet/www#4]
All   
Branding   
Content   
Environmental    
Digital   
Print 
Motion

**Comment by joshreisner** [comment]
You should really do these. I started it but had enough questions with 6th Borough Market and DDC that I thought I should stop.

Just use the Types area pictured below. The subnav is generated from the active types in use.

![screen shot 2016-06-14 at 10 31 07 am](https://cloud.githubusercontent.com/assets/1551689/16052884/20655158-321b-11e6-9aac-7fd3f122b5ce.png)

**Comment by katejhowe** [comment]
Ok, all done. I wonder if each set looks lite when they are broken up this way? May have to add more content...
