### ISSUE TITLE
teach kate to edit font sizes in window

### ISSUE THREAD

**Issue by katejhowe** [better-yet/www#5]

**Comment by joshreisner** [comment]
So use Chrome first of all, because it's the best at this. Then hit command-shift-c and the 'DevTools' should appear at the bottom of the screen. Move your cursor over the page and the various elements should be highlighted. Click the one you want to tweak.

![screen shot 2016-06-14 at 10 33 09 am](https://cloud.githubusercontent.com/assets/1551689/16053011/cdf6f11e-321b-11e6-910f-161717f8d1fc.png)

Now note the styles window in the bottom right. That's got each of the CSS properties that you can adjust. Scroll down until you see font-size. Click on the value, and use the up and down cursor keys to adjust it. You should see the values changing in the window above. (Tip: hold down shift while you're doing that to move in increments of 10.)

![screen shot 2016-06-14 at 10 34 08 am](https://cloud.githubusercontent.com/assets/1551689/16053125/519205a4-321c-11e6-8b3e-e79bebee6851.png)

Now make a note of what you think the value should be and let me know. You can tweak other values, like margin, padding, color, line-height, letter-spacing, etc.

**Comment by katejhowe** [comment]
Let's try these adjustments:

NAV
Top nav : 18pt
sub nav: 10pt
The underline under the Top Nav (Better Yet Studio / Projects) is too thick… 

PROJECT PAGES:
Project title: 16px, track out slightly
Tags: 11px, underline
Project description: 10pt
Align the top image and the top of the text box
Less padding between the images - 1/4 to 1/3 of current 

Profile, Service Pages
Big text: 26px; 1.3 line height

**Comment by katejhowe** [comment]
Question for you - is the gray page color the same on all the pages? It is looking tinted toward the accent color to me, but I think it make just be an optical effect!

**Comment by joshreisner** [comment]
yep! 4% black on every page.

**Comment by joshreisner** [comment]
I’m assuming you mean ‘px’ for all the measurements below…

**Comment by katejhowe** [comment]
yes - px!


On Wed, Jun 15, 2016 at 10:27 AM, Josh Reisner <notifications@github.com>
wrote:

> I’m assuming you mean ‘px’ for all the measurements below…
>
> > On Jun 15, 2016, at 7:22 AM, Josh Reisner <josh@joshreisner.com> wrote:
> >
> > yep! 4% black on every page.
> >
> >> On Jun 15, 2016, at 3:36 AM, katejhowe <notifications@github.com
> <mailto:notifications@github.com>> wrote:
> >>
> >> Question for you - is the gray page color the same on all the pages? It
> is looking tinted toward the accent color to me, but I think it make just
> be an optical effect!
> >>
> >> —
> >> You are receiving this because you commented.
> >> Reply to this email directly, view it on GitHub <
> https://github.com/better-yet/www/issues/5#issuecomment-226150581>, or
> mute the thread <
> https://github.com/notifications/unsubscribe/ABetSaJ96VRBqALL5pJM6R3d3gSuVwnSks5qL9XCgaJpZM4I1h9B
> >.
> >>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/better-yet/www/issues/5#issuecomment-226204229>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AS-I489KLDj_-uoGAI0_k3JYtNKPvaiaks5qMAvngaJpZM4I1h9B>
> .
>



-- 
- - - - - - - - - - - - - - - - - - - - - - - - - - -
kate howe makes things
- - - - - - - - - - - - - - - - - - - - - - - - - - -
tel. 1 203 415 0578
www.katehowemakesthings.com
- - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by joshreisner** [comment]
On second thought, I think you meant px where you said px and pt where you said pt, so I implemented them as is.

Font underlines come from the font, so now that we've changed the font-size of the heading it should be a little thinner.

**Comment by joshreisner** [comment]
Oh, are you sure? I tried px but it was a lot smaller. Pt was just slightly smaller.

**Comment by katejhowe** [comment]
Yes I think so. i was doing it in the browser, so that all would have been
specified in px...


On Wed, Jun 15, 2016 at 10:43 AM, Josh Reisner <notifications@github.com>
wrote:

> Oh, are you sure? I tried px but it was a lot smaller. Pt was just
> slightly smaller.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/better-yet/www/issues/5#issuecomment-226209021>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AS-I4_2qyAYC-0ku9Qy16a5nGPILWY8gks5qMA98gaJpZM4I1h9B>
> .
>



-- 
- - - - - - - - - - - - - - - - - - - - - - - - - - -
kate howe makes things
- - - - - - - - - - - - - - - - - - - - - - - - - - -
tel. 1 203 415 0578
www.katehowemakesthings.com
- - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by katejhowe** [comment]
Ok cool! Couple  more tweaks...
NAV
tighten up the space around the "  /  " - maybe 2 spaces on each side
bring up top hangline of page content (projects / text) about 50%
Project title on the main Projects page should also be 10px 

PROJECT PAGES:
I'm struggling a bit here with how differently the browsers display the same fonts! check out screen grabs - Chrome looks like its bold, and its pretty difficult to read, whereas Safari is lighter and its much better... I think its partially the font that's making it hard to read however.
- Can we try Moderat at 12px, line height 1.3 for the project text
- then shift the tags to Roboto 10px
![screen shot 2016-06-15 at 11 26 33 am](https://cloud.githubusercontent.com/assets/19892451/16086055/38e4d1f0-32ec-11e6-8e47-a357441ee91c.png)
![screen shot 2016-06-15 at 11 21 43 am](https://cloud.githubusercontent.com/assets/19892451/16086056/3904b812-32ec-11e6-9b17-8273ea9e627a.png)

**Comment by joshreisner** [comment]
I just brought up the top hangline before I saw this, what do you think of it now?

**Comment by joshreisner** [comment]
Ok, the fonts should be looking more like safari now in Chrome. Before on top, after on bottom.

![screen shot 2016-06-15 at 8 52 07 am](https://cloud.githubusercontent.com/assets/1551689/16087073/91f30eb2-32d6-11e6-88cb-852d1664a1d1.png)

**Comment by katejhowe** [comment]
Yes I see that - great! I think the Moderat text should be tracked in a
hair, and that would help with legibility. Letter-spacing 0px (except in
the CAP project titles).

The hangline looks good. I think we could loose a small amount of padding
at the top - 20-20% of what's there.

This is really well! What do you think?

On Wed, Jun 15, 2016 at 11:53 AM, Josh Reisner <notifications@github.com>
wrote:

> Ok, the fonts should be looking more like safari now in Chrome. Before on
> top, after on bottom.
>
> [image: screen shot 2016-06-15 at 8 52 07 am]
> <https://cloud.githubusercontent.com/assets/1551689/16087073/91f30eb2-32d6-11e6-88cb-852d1664a1d1.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/better-yet/www/issues/5#issuecomment-226232030>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AS-I485ZqY19vZNUCzTdbrSj_vQTgnrfks5qMB_1gaJpZM4I1h9B>
> .
>



-- 
- - - - - - - - - - - - - - - - - - - - - - - - - - -
kate howe makes things
- - - - - - - - - - - - - - - - - - - - - - - - - - -
tel. 1 203 415 0578
www.katehowemakesthings.com
- - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by joshreisner** [comment]
Yes, I'm excited! I took the letter spacing and top padding in. The letter spacing used to be 1px globally and 2px in the CAP project titles, now it's just 2px in the CAP project titles.
