### ISSUE TITLE
scrolling on project pages

### ISSUE THREAD

**Issue by katejhowe** [better-yet/www#6]
(This may already have been on your to-do list...)

level 0: watermark stays stationary on the bottom
level 1: images scroll up
level 2: navigation and project description stay stationary

**Comment by joshreisner** [comment]
Yes. Does it only apply to the inside project page? Should the nav always be fixed, such as on the project list page? What if the 'services' text were long enough to scroll?

**Comment by katejhowe** [comment]
I think the nav should always be fixed...

On Tue, Jun 14, 2016 at 2:15 PM, Josh Reisner <notifications@github.com>
wrote:

> Yes. Does it only apply to the inside project page? Should the nav always
> be fixed, such as on the project list page? What if the 'services' text
> were long enough to scroll?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/better-yet/www/issues/6#issuecomment-225968912>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AS-I47am36ausIY4gW7qvumcPcf1Z_3xks5qLu_ZgaJpZM4I1iLu>
> .
>



-- 
- - - - - - - - - - - - - - - - - - - - - - - - - - -
kate howe makes things
- - - - - - - - - - - - - - - - - - - - - - - - - - -
tel. 1 203 415 0578
www.katehowemakesthings.com
- - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by joshreisner** [comment]
Ok sounds good.

**Comment by katejhowe** [comment]
n-iiicee!

On Tue, Jun 14, 2016 at 6:13 PM, Josh Reisner <notifications@github.com>
wrote:

> Closed #6 <https://github.com/better-yet/www/issues/6> via d10a23e
> <https://github.com/better-yet/www/commit/d10a23e227c0ed46578625cabb3d5e92e548ed83>
> .
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/better-yet/www/issues/6#event-692517783>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AS-I4_2e-h1whnDSWbn4G4AWJ0tycQaXks5qLyeggaJpZM4I1iLu>
> .
>



-- 
- - - - - - - - - - - - - - - - - - - - - - - - - - -
kate howe makes things
- - - - - - - - - - - - - - - - - - - - - - - - - - -
tel. 1 203 415 0578
www.katehowemakesthings.com
- - - - - - - - - - - - - - - - - - - - - - - - - - -
